ci:
    autoupdate_schedule: quarterly

repos:
    - repo: https://github.com/pycqa/isort
      rev: 6.1.0
      hooks:
          - id: isort
            files: eeg_flow

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.13.3
      hooks:
          - id: ruff
            name: ruff linter
            args: [--fix]
            files: eeg_flow
          - id: ruff-format
            name: ruff formatter
            files: eeg_flow

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            args: [--write-changes]
            additional_dependencies: [tomli]

    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            files: eeg_flow
            additional_dependencies: [tomli]

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.24.3
      hooks:
          - id: toml-sort-fix
            files: pyproject.toml

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|.codecov.yaml|.pre-commit-config.yaml|.yamllint.yaml)
